version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: personal-finance-db
    environment:
      POSTGRES_DB: personalfinance
      POSTGRES_USER: personalfinance
      POSTGRES_PASSWORD: personalfinance
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
